# Generated by Django 5.1.2 on 2025-07-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoleitura',
            name='motivo_saida',
            field=models.CharField(choices=[('pdi', 'Por PDI'), ('pediu', 'Pediu para sair'), ('transferido', 'Interno Transferido'), ('alvara', 'Alvará')], max_length=50),
        ),
    ]
