# Generated by Django 5.1.2 on 2025-07-12 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0002_alter_historicoleitura_motivo_saida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicoleitura',
            name='data_saida',
            field=models.DateField(),
        ),
    ]
