# Generated by Django 5.1.2 on 2025-07-27 15:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0003_alter_historicoleitura_data_saida'),
    ]

    operations = [
        migrations.AddField(
            model_name='filadeespera',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frentedeleitura',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
