# Generated by Django 5.1.2 on 2025-08-17 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0005_historicoleitura_created_at'),
        ('painel', '0068_remove_pessoa_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='filadeespera',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='frentedeleitura',
            name='livros_lidos',
        ),
        migrations.RemoveField(
            model_name='historicoleitura',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicoleitura',
            name='livros_lidos',
        ),
        migrations.AddField(
            model_name='historicoleitura',
            name='ciclo',
            field=models.CharField(default='Ciclo 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='filadeespera',
            name='pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fila_espera', to='painel.pessoa'),
        ),
        migrations.AlterField(
            model_name='historicoleitura',
            name='data_saida',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='historicoleitura',
            name='motivo_saida',
            field=models.CharField(choices=[('concluido', 'Concluiu o ciclo'), ('transferencia', 'Transferência'), ('outro', 'Outro motivo')], max_length=20),
        ),
        migrations.CreateModel(
            name='CicloLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(choices=[(1, 'Janeiro'), (2, 'Fevereiro'), (3, 'Março'), (4, 'Abril'), (5, 'Maio'), (6, 'Junho'), (7, 'Julho'), (8, 'Agosto'), (9, 'Setembro'), (10, 'Outubro'), (11, 'Novembro'), (12, 'Dezembro')])),
                ('ano', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ['ano', 'mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_leitura', models.DateField(auto_now_add=True)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leitura.cicloleitura')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='painel.pessoa')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leitura.livro')),
            ],
            options={
                'ordering': ['ciclo', 'livro'],
                'unique_together': {('pessoa', 'livro', 'ciclo')},
            },
        ),
    ]
