# Generated by Django 5.1.2 on 2025-08-17 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0006_livro_remove_filadeespera_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frentedeleitura',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leitura.cicloleitura'),
        ),
        migrations.AddField(
            model_name='frentedeleitura',
            name='livro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leitura.livro'),
        ),
    ]
