# Generated by Django 5.1.2 on 2025-08-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0007_frentedeleitura_ciclo_frentedeleitura_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicoleitura',
            name='livros_lidos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
