# Generated by Django 5.1.2 on 2025-08-17 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0008_historicoleitura_livros_lidos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frentedeleitura',
            name='livro',
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('disponivel', models.BooleanField(default=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemplares', to='leitura.livro')),
            ],
        ),
        migrations.AddField(
            model_name='frentedeleitura',
            name='exemplar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leitura.exemplar'),
        ),
    ]
