# Generated by Django 5.1.2 on 2025-09-07 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0009_remove_frentedeleitura_livro_exemplar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='exemplar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leitura.exemplar'),
        ),
    ]
