# Generated by Django 5.1.2 on 2024-11-12 14:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(choices=[('A', 'Bloco A'), ('B', 'Bloco B'), ('C', 'Bloco C'), ('D', 'Bloco D'), ('E', 'Bloco E')], max_length=1, null=True)),
                ('cela', models.CharField(choices=[('1', 'Cela 1'), ('2', 'Cela 2'), ('3', 'Cela 3'), ('4', 'Cela 4'), ('5', 'Cela 5'), ('6', 'Cela 6'), ('7', 'Cela 7')], max_length=2, null=True)),
                ('nome_completo', models.CharField(max_length=255, null=True)),
                ('idade', models.IntegerField(null=True)),
                ('data_entrada', models.DateField(null=True)),
                ('escolaridade', models.CharField(choices=[('1', 'Fundamental Incompleto'), ('2', 'Fundamental Completo'), ('3', 'Médio Incompleto'), ('4', 'Médio Completo'), ('5', 'Superior Incompleto'), ('6', 'Superior Completo')], max_length=1, null=True)),
                ('estudando', models.CharField(choices=[('nao_estuda', 'Não Estuda'), ('ibraema', 'IBRAEMA'), ('eja_i', 'EJA I'), ('eja_ii', 'EJA II'), ('eja_iii', 'EJA III')], max_length=255, null=True)),
                ('sancao_disciplinar', models.BooleanField(default=False)),
                ('tipo_sancao', models.CharField(blank=True, choices=[('sem_castelo', 'Sem Castelo'), ('sem_visita_intima', 'Sem Visita Íntima'), ('sem_visita_social', 'Sem Visita Social')], max_length=20, null=True)),
                ('sancao_disciplinar_descricao', models.TextField(blank=True, null=True)),
                ('data_inicio_sancao', models.DateTimeField(blank=True, null=True)),
                ('data_fim_sancao', models.DateTimeField(blank=True, null=True)),
                ('artigo_criminal', models.CharField(max_length=255, null=True)),
                ('cidade', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoAlteracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_alterado', models.CharField(max_length=50)),
                ('valor_antigo', models.CharField(max_length=100)),
                ('valor_novo', models.CharField(max_length=100)),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_alteracoes', to='painel.pessoa')),
            ],
        ),
    ]
