# Generated by Django 5.1.2 on 2024-11-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0002_rename_data_fim_sancao_pessoa_fim_sancao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='fim_sancao',
            new_name='data_fim_sancao',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='inicio_sancao',
            new_name='data_inicio_sancao',
        ),
    ]
