# Generated by Django 5.1.2 on 2024-11-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0008_transferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transferencia',
            name='responsavel',
        ),
    ]
