# Generated by Django 5.1.2 on 2024-11-18 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0010_pessoa_tem_transferencia_ativa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transferencia',
            options={},
        ),
        migrations.AddField(
            model_name='transferencia',
            name='transferencia_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='data_transferencia',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='justificativa',
            field=models.TextField(default='Sem justificativa'),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='penitenciaria_destino',
            field=models.CharField(default='Não Definido', max_length=255),
        ),
        migrations.AlterField(
            model_name='transferencia',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel.pessoa'),
        ),
    ]
