# Generated by Django 5.1.2 on 2024-11-19 15:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0014_pessoa_data_fim_sancao_pessoa_data_inicio_sancao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
