# Generated by Django 5.1.2 on 2024-11-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0021_alter_eletronico_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='escolaridade',
            field=models.CharField(choices=[('1', 'E.F.I incompleto'), ('2', 'E.F.C'), ('3', 'E.M.I'), ('4', 'E.M.C'), ('5', 'E.S.I'), ('6', 'E.S.C')], max_length=1, null=True),
        ),
    ]
