# Generated by Django 5.1.2 on 2024-12-07 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0026_alter_foto_quantidade_fotos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Foto',
        ),
    ]
