# Generated by Django 5.1.2 on 2024-12-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0030_pdi_numero_ocorrencia_pdi_numero_pdi_pdi_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdi',
            name='resultado',
            field=models.CharField(blank=True, choices=[('andamento', 'Andamento'), ('condenado', 'Condenado'), ('sobrestado', 'Sobrestado')], max_length=20, verbose_name='Resultado'),
        ),
    ]
