# Generated by Django 5.1.2 on 2024-12-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0031_alter_pdi_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdi',
            name='natureza',
            field=models.CharField(blank=True, choices=[('leve', 'Leve'), ('media', 'Média'), ('grave', 'Grave')], max_length=50),
        ),
    ]
