# Generated by Django 5.1.2 on 2024-12-14 14:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0032_alter_pdi_natureza'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('warning', 'Aviso'), ('info', 'Informação'), ('success', 'Sucesso'), ('error', 'Erro')], default='info', max_length=50)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('lida', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
