# Generated by Django 5.1.2 on 2025-02-18 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0038_alter_pessoa_frente_trabalho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='frente_trabalho',
        ),
        migrations.CreateModel(
            name='FrenteDeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frente_trabalho', models.CharField(choices=[('nao_trabalha', 'Não há'), ('horta', 'Horta'), ('piscicultura', 'Piscicultura'), ('minhocario', 'Minhocário'), ('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('fabrica_blocos', 'Fáb. de Blocos'), ('croche', 'Crochê'), ('digitalizador', 'Digitalizador'), ('bibliotecario', 'Bibliotecário'), ('facilitador', 'Facilitador')], default='nao_trabalha', max_length=50)),
                ('data_inicio', models.DateField()),
                ('numero_portaria_admissao', models.CharField(max_length=50)),
                ('data_retroacao', models.DateField(blank=True, null=True)),
                ('data_revogacao', models.DateField(blank=True, null=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frentes_de_trabalho', to='painel.pessoa')),
            ],
        ),
    ]
