# Generated by Django 5.1.2 on 2025-02-19 14:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0039_remove_pessoa_frente_trabalho_frentedetrabalho'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='A matrícula deve conter apenas números (até 10 dígitos).', regex='^\\d{1,30}$')]),
        ),
    ]
