# Generated by Django 5.1.2 on 2025-02-19 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0040_pessoa_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='idade',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
