# Generated by Django 5.1.2 on 2025-02-21 16:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0043_alter_pessoa_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='A matrícula deve conter apenas números (até 30 dígitos).', regex='^\\d{1,30}$')]),
        ),
    ]
