# Generated by Django 5.1.2 on 2025-02-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0046_alter_frentedetrabalho_numero_portaria_revogacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frentedetrabalho',
            name='numero_portaria_revogacao',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
