# Generated by Django 5.1.2 on 2025-02-26 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0049_pessoa_pdf_revogacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='pdf_revogacao',
        ),
        migrations.AddField(
            model_name='frentedetrabalho',
            name='pdf_revogacao',
            field=models.FileField(blank=True, null=True, upload_to='revogacoes/'),
        ),
    ]
