# Generated by Django 4.2 on 2025-04-01 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0052_pedagogiaprisional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedagogiaprisional',
            name='dias_remissao',
        ),
    ]
