# Generated by Django 4.2 on 2025-04-01 16:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0054_rename_data_leitura_pedagogiaprisional_data_inclusao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaEsperaLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada_fila', models.DateField(default=django.utils.timezone.now)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fila_espera', to='painel.pessoa')),
            ],
        ),
    ]
