# Generated by Django 5.1.2 on 2025-07-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0058_alter_frentedetrabalho_numero_portaria_revogacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frentedetrabalho',
            name='numero_portaria_revogacao',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
