# Generated by Django 5.1.2 on 2025-07-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0059_alter_frentedetrabalho_numero_portaria_revogacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frentedetrabalho',
            name='frente_trabalho',
            field=models.CharField(choices=[('nao_trabalha', 'Não há'), ('horta', 'Horta'), ('piscicultura', 'Piscicultura'), ('minhocario', 'Minhocário'), ('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('fabrica_blocos', 'Fáb. de Blocos'), ('croche', 'Crochê'), ('digitalizador', 'Digitalizador'), ('bibliotecario', 'Bibliotecário'), ('facilitador', 'Facilitador'), ('servicos_gerais', 'Serviços Gerais')], default='nao_trabalha', max_length=50),
        ),
    ]
