# Generated by Django 5.1.2 on 2025-07-11 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0060_alter_frentedetrabalho_frente_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sancao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('sem_castelo', 'Sem Castelo'), ('sem_visita_intima', 'Sem Visita Íntima'), ('sem_visita_social', 'Sem Visita Social'), ('isolamento_preventivo', 'Isolamento Preventivo')], max_length=50),
        ),
    ]
