# Generated by Django 5.1.2 on 2025-07-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0063_alter_sancao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='estudando',
            field=models.CharField(choices=[('nao_estuda', 'N/A'), ('ibraema', 'IBRAEMA'), ('eja_i', 'EJA I'), ('eja_ii', 'EJA II'), ('eja_iii', 'EJA III'), ('ensino_superior', 'Ensino Superior')], max_length=255, null=True),
        ),
    ]
