# Generated by Django 5.1.2 on 2025-07-12 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0064_alter_pessoa_estudando'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedagogiaPrisional',
        ),
    ]
