# Generated by Django 5.1.2 on 2025-07-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0065_delete_pedagogiaprisional'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
