# Generated by Django 5.1.2 on 2025-07-27 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0067_pessoa_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cpf',
        ),
    ]
