# Generated by Django 5.1.2 on 2025-08-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comunicado',
            options={'ordering': ['-criado_em']},
        ),
    ]
