# Generated by Django 5.1.2 on 2025-09-21 14:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comunicados', '0002_alter_comunicado_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='conteudo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
