# Generated by Django 5.1.2 on 2025-07-16 13:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('painel', '0059_delete_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alvara', 'Alvará'), ('transferencia', 'Transferência'), ('revogacao', 'Revogação de Frente'), ('pdi', 'PDI')], default='pdi', max_length=20)),
                ('titulo', models.CharField(max_length=255)),
                ('mensagem', models.TextField()),
                ('grau', models.CharField(choices=[('geral', 'Geral'), ('importante', 'Importante')], default='geral', max_length=15)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='painel.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='NotificacaoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lida', models.BooleanField(default=False)),
                ('notificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notification.notificacao')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('notificacao', 'usuario')},
            },
        ),
        migrations.AddField(
            model_name='notificacao',
            name='usuarios',
            field=models.ManyToManyField(related_name='notificacoes', through='notification.NotificacaoUsuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
