# Generated by Django 5.1.2 on 2025-08-17 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('painel', '0060_delete_pedagogiaprisional'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilaDeEspera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inclusao', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fila_leitura', to='painel.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='FrenteDeLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField(auto_now_add=True)),
                ('livros_lidos', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='frente_leitura', to='painel.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoLeitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_saida', models.DateField()),
                ('motivo_saida', models.CharField(choices=[('pdi', 'Por PDI'), ('pediu', 'Pediu para sair'), ('transferido', 'Interno Transferido'), ('alvara', 'Alvará')], max_length=50)),
                ('livros_lidos', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_leitura', to='painel.pessoa')),
            ],
        ),
    ]
