# Generated by Django 5.1.2 on 2025-09-14 12:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0003_leitura_exemplar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cicloleitura',
            options={'ordering': ['inicio']},
        ),
        migrations.AlterUniqueTogether(
            name='cicloleitura',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cicloleitura',
            name='fim',
            field=models.DateField(default='2025-09-30'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cicloleitura',
            name='inicio',
            field=models.DateField(default='2025-09-01'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='cicloleitura',
            name='ano',
        ),
        migrations.RemoveField(
            model_name='cicloleitura',
            name='mes',
        ),
    ]
