# Generated by Django 5.1.2 on 2025-09-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0004_alter_cicloleitura_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicloleitura',
            name='fim',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cicloleitura',
            name='inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
