# Generated by Django 5.1.2 on 2025-09-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0005_alter_cicloleitura_fim_alter_cicloleitura_inicio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cicloleitura',
            options={'ordering': ['ano', 'numero']},
        ),
        migrations.AddField(
            model_name='cicloleitura',
            name='ano',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='cicloleitura',
            name='numero',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='cicloleitura',
            unique_together={('numero', 'ano')},
        ),
    ]
