# Generated by Django 5.1.2 on 2025-09-14 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0006_alter_cicloleitura_options_cicloleitura_ano_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='ciclo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leitura.cicloleitura'),
        ),
    ]
