# Generated by Django 5.1.2 on 2025-09-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leitura', '0007_alter_leitura_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='leitura',
            name='ciclo_indefinido',
            field=models.BooleanField(default=False),
        ),
    ]
