# Generated by Django 5.1.2 on 2024-11-12 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_fim_sancao',
            new_name='fim_sancao',
        ),
        migrations.RenameField(
            model_name='pessoa',
            old_name='data_inicio_sancao',
            new_name='inicio_sancao',
        ),
    ]
