# Generated by Django 5.1.2 on 2024-11-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0003_rename_fim_sancao_pessoa_data_fim_sancao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='frente_trabalho',
            field=models.CharField(blank=True, choices=[('horta', 'Horta'), ('piscicultura', 'Piscicultura'), ('minhocario', 'Minhocário'), ('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('fabrica_blocos', 'Fábrica de Blocos'), ('croche', 'Crochê')], max_length=20, null=True),
        ),
    ]
