# Generated by Django 5.1.2 on 2024-11-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0009_remove_transferencia_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='tem_transferencia_ativa',
            field=models.BooleanField(default=False),
        ),
    ]
