# Generated by Django 5.1.2 on 2024-11-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0011_alter_transferencia_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencia',
            name='data_transferencia',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
