# Generated by Django 5.1.2 on 2024-11-19 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0012_alter_transferencia_data_transferencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data_fim_sancao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_inicio_sancao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='sancao_disciplinar',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='sancao_disciplinar_descricao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='tipo_sancao',
        ),
        migrations.CreateModel(
            name='SancaoDisciplinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('sem_castelo', 'Sem Castelo'), ('sem_visita_intima', 'Sem Visita Íntima'), ('sem_visita_social', 'Sem Visita Social')], max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sancoes', to='painel.pessoa')),
            ],
        ),
    ]
