# Generated by Django 5.1.2 on 2024-11-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0017_alter_sancao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sancao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('sem_castelo', 'Sem Castelo'), ('sem_visita_intima', 'Sem Visita Íntima'), ('sem_visita_social', 'Sem Visita Social')], max_length=50),
        ),
    ]
