# Generated by Django 5.1.2 on 2024-11-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0018_alter_sancao_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='data_fim_sancao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='data_inicio_sancao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='sancao_disciplinar',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='sancao_disciplinar_descricao',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='tipo_sancao',
        ),
    ]
