# Generated by Django 5.1.2 on 2024-11-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0020_eletronico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eletronico',
            name='tipo',
            field=models.CharField(blank=True, choices=[('tv', 'Tv'), ('radio', 'Rádio'), ('ventilador', 'Ventilador')], max_length=50),
        ),
    ]
