# Generated by Django 5.1.2 on 2024-12-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0025_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='quantidade_fotos',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 Foto'), (2, '2 Fotos'), (3, '3 Fotos')], default=1),
        ),
    ]
