# Generated by Django 5.1.2 on 2024-12-12 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0029_pdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdi',
            name='numero_ocorrencia',
            field=models.CharField(default='OCC-0000', max_length=20, verbose_name='Nº Ocorrência'),
        ),
        migrations.AddField(
            model_name='pdi',
            name='numero_pdi',
            field=models.CharField(default='PDI-0000', max_length=20, verbose_name='Nº PDI'),
        ),
        migrations.AddField(
            model_name='pdi',
            name='resultado',
            field=models.CharField(blank=True, choices=[('andamento', 'Andamento'), ('condenado', 'Condenado')], max_length=20, verbose_name='Resultado'),
        ),
    ]
