# Generated by Django 5.1.2 on 2024-12-15 14:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0033_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
