# Generated by Django 5.1.2 on 2025-01-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0035_pessoa_saiu_temporariamente'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='albergado',
            field=models.BooleanField(default=False),
        ),
    ]
