# Generated by Django 5.1.2 on 2025-02-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0036_pessoa_albergado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('foragido', 'Foragido')], default='ativo', max_length=10),
        ),
    ]
