# Generated by Django 5.1.2 on 2025-02-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0037_pessoa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='frente_trabalho',
            field=models.CharField(choices=[('nao_trabalha', 'Não há'), ('horta', 'Horta'), ('piscicultura', 'Piscicultura'), ('minhocario', 'Minhocário'), ('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('fabrica_blocos', 'Fáb. de Blocos'), ('croche', 'Crochê'), ('digitalizador', 'Digitalizador'), ('bibliotecario', 'Bibliotecário'), ('facilitador', 'Facilitador')], max_length=20),
        ),
    ]
