# Generated by Django 5.1.2 on 2025-02-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0041_remove_pessoa_idade_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='frentedetrabalho',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('revogado', 'Revogado')], default='ativo', max_length=10),
        ),
    ]
