# Generated by Django 5.1.2 on 2025-02-22 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0044_alter_pessoa_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='frentedetrabalho',
            name='numero_portaria_revogacao',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
