# Generated by Django 5.1.2 on 2025-02-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0047_alter_frentedetrabalho_numero_portaria_revogacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frentedetrabalho',
            name='numero_portaria_revogacao',
            field=models.CharField(default='N/A', max_length=50, unique=True),
        ),
    ]
