# Generated by Django 5.1.2 on 2025-02-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0048_alter_frentedetrabalho_numero_portaria_revogacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='pdf_revogacao',
            field=models.FileField(blank=True, null=True, upload_to='revogacoes/'),
        ),
    ]
