# Generated by Django 5.1.2 on 2025-03-04 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0050_remove_pessoa_pdf_revogacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='matricula',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='A matrícula deve conter apenas números (até 10 dígitos).', regex='^\\d{1,30}$')]),
        ),
    ]
