# Generated by Django 4.2 on 2025-04-01 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0051_alter_pessoa_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedagogiaPrisional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esta_na_frente_leitura', models.BooleanField(default=False)),
                ('data_leitura', models.DateField(blank=True, null=True)),
                ('livros_lidos', models.PositiveIntegerField(default=0)),
                ('dias_remissao', models.PositiveIntegerField(default=0)),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedagogia', to='painel.pessoa')),
            ],
        ),
    ]
