# Generated by Django 4.2 on 2025-04-01 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0053_remove_pedagogiaprisional_dias_remissao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedagogiaprisional',
            old_name='data_leitura',
            new_name='data_inclusao',
        ),
        migrations.AddField(
            model_name='pedagogiaprisional',
            name='data_saida',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedagogiaprisional',
            name='motivo_saida',
            field=models.CharField(blank=True, choices=[('PDI', 'Por PDI'), ('Pediu', 'Pediu para sair')], max_length=50, null=True),
        ),
    ]
