# Generated by Django 4.2 on 2025-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0055_filaesperaleitura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedagogiaprisional',
            old_name='esta_na_frente_leitura',
            new_name='saiu_da_leitura',
        ),
        migrations.AddField(
            model_name='pedagogiaprisional',
            name='lista',
            field=models.CharField(choices=[('frente', 'Frente de Leitura'), ('espera', 'Fila de Espera')], default='espera', max_length=10),
        ),
        migrations.DeleteModel(
            name='FilaEsperaLeitura',
        ),
    ]
