# Generated by Django 5.1.2 on 2025-07-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0056_rename_esta_na_frente_leitura_pedagogiaprisional_saiu_da_leitura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frentedetrabalho',
            name='numero_portaria_revogacao',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
