# Generated by Django 5.1.2 on 2025-07-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0057_alter_frentedetrabalho_numero_portaria_revogacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frentedetrabalho',
            name='frente_trabalho',
            field=models.CharField(choices=[('nao_trabalha', 'Não há'), ('horta', 'Horta'), ('piscicultura', 'Piscicultura'), ('minhocario', 'Minhocário'), ('limpeza', 'Limpeza'), ('manutencao', 'Manutenção'), ('fabrica_blocos', 'Fáb. de Blocos'), ('croche', 'Crochê'), ('digitalizador', 'Digitalizador'), ('bibliotecario', 'Bibliotecário'), ('facilitador', 'Facilitador'), ('servicos_gerais', 'Serviços Gerais')], default='nao_trabalha', max_length=50),
        ),
        migrations.AlterField(
            model_name='sancao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('sem_castelo', 'Sem Castelo'), ('sem_visita_intima', 'Sem Visita Íntima'), ('sem_visita_social', 'Sem Visita Social'), ('isolamento_preventivo', 'Isolamento Preventivo'), ('isolamento_reflexao', 'Isolamento Reflexivo')], max_length=50),
        ),
    ]
