# Generated by Django 5.1.2 on 2025-07-16 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0058_alter_frentedetrabalho_frente_trabalho_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
