# Generated by Django 5.1.2 on 2025-08-17 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('painel', '0059_delete_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PedagogiaPrisional',
        ),
    ]
